language : bash
env:
    global:
      - HUB_PROTOCOL=https
      #GITHUB_TOKEN
      - secure: "wAV9U0ZFAIvUE0YVWQkjUpbgXHCZd711/FfelIAS61+ZDR2zcEf7eIClgMB3XX1Ck7LX0lSnt7SgrNDW9JxV7QNgKO3iBt8ZE10r06isdun4WWNtgPyTSSRKAfiUR3iVTRZFDWmGC4e434KhJ5wqqZXp5kFbXeSj897JqdJigq0jrkeLEafhvTfkVvnPrWWkoIQ9MZ5GJ0FnRjpV+3hLSWOH6rptUYrMaIfUEhQ8jbAX0vCJ2vk3q0s+BQaW3F6kJD9nIiUzbre0xHKmWZuhwk1w3FpoKasugJ2Emq+WP/t6BRe9OIQ7O9AzbkoP/xbFlkPI9iXTfcuC9zwtksRUYOYry8GyGSyaDxVUqi+LKAGcsTOc5jZXA/s5zXViFSHS+gnH6UAB2n5WJXmmkKX51lqAuYQeybWE8BJcXjMy4/pIHW+jBWPwmxQCcV2rMMf4SQVYmRCgchwJFtMpvS79tILuX6oYQ5v/VdFvX4HDbsx1ikKXiYFDY5a68uPFohiJrCXdtHgjucL8RaHU0SdI9LJ0TX/rlo9Douwh6arh3J2w8W/ICOfNMfPnKRolq34yZ9p1x4SlzNDHbdHBhPja7Sjzea0D+v3UN5Dd50TEZd9BQ0iutug5cowiw+ew3tYocSSyAqFXj7y0Bw5CcTSFTg5/tsWdT5lOVHNRqnMo9w8="
branches:
  except:
  - nightly
git:
  quiet: true
before_install:
    - curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
    - sudo apt-get -qq update
    - sudo apt-get install -y debhelper devscripts fakeroot build-essential po-debconf gh
    - openssl aes-256-cbc -K $encrypted_2155243bff9e_key -iv $encrypted_2155243bff9e_iv -in 077CC9F2.gpg.enc -out 077CC9F2.gpg -d
    - gpg --import 077CC9F2.gpg
install:
    - debuild '-k9D1DC8DD077CC9F2'
deploy:
    - provider: releases
      skip_cleanup: true
      file_glob: true
      file: "../*.deb"
      api_key:
          secure: "rZlXMZQ2Z9snCaKF8DfEtpTx6N3j7SrDDH9ASlaxKGken++5wzlp4UyafPPdsFMXRpDrfI5OZOr6UcyKDrh5Pgwug5RVEqg5gK5b4NcTHka4Zmfvx0fq0d6HLFZ+/Cw0MMUsO2YT18TDAh/sjFRO+yxOEONhUP/sMb13Zds1FALsowkcHMrVbM8+Ue8rJIQo7WombyLH7wyJvdxtQErEwwMVsJF1dwMqF47rs5pxVqDqSOMDDStnEpuARWmWcP6B+dFIyV2ekCmZ19jnSL58pJNkZ/YMDR2/mmOx4mHnunPLdN6hiZenNJJ1M8O7Nex7wTiQgiz88+9GimQ8vU1p+U+K8Bm0UH8JOdFbyhQYvAaktZlv+geGbcigIgDjn5nXuXhe4p5PCs+PrHEzFmbE+gzpUcgUflmjD5oof05BFaf7N/IWtN3G/qOF2DKb2xCON9ihPUfN3bHPv/af+928S4Z2LabasveclzGSmLvgz4S5csO7lm0TyHotC0+MyYmDKYaNMoWZngFI4OgyF2ZcB5uBd4cag5hVPKYXGWZZseTe2OWQuR8IsaA9o2hXH91zv2C9n4cmGgXbe6INvSKWQKl3dCYmtpIcXEXkAiLhMsD5z9FQUle39azVAjKMcb+K1xgyp+7m1mcdHEohPqV3CQjN1GuP/r31HD2wujqfe0k="
      on:
          tags: true
    - provider: releases
      skip_cleanup: true
      file_glob: true
      file: "../*.deb"
      tag_name: "nightly"
      prerelease: true
      name: Automatic nightly build by Travis on $(date +'%F %T %Z').
      target_commitish: $TRAVIS_COMMIT
      api_key:
          secure: "rZlXMZQ2Z9snCaKF8DfEtpTx6N3j7SrDDH9ASlaxKGken++5wzlp4UyafPPdsFMXRpDrfI5OZOr6UcyKDrh5Pgwug5RVEqg5gK5b4NcTHka4Zmfvx0fq0d6HLFZ+/Cw0MMUsO2YT18TDAh/sjFRO+yxOEONhUP/sMb13Zds1FALsowkcHMrVbM8+Ue8rJIQo7WombyLH7wyJvdxtQErEwwMVsJF1dwMqF47rs5pxVqDqSOMDDStnEpuARWmWcP6B+dFIyV2ekCmZ19jnSL58pJNkZ/YMDR2/mmOx4mHnunPLdN6hiZenNJJ1M8O7Nex7wTiQgiz88+9GimQ8vU1p+U+K8Bm0UH8JOdFbyhQYvAaktZlv+geGbcigIgDjn5nXuXhe4p5PCs+PrHEzFmbE+gzpUcgUflmjD5oof05BFaf7N/IWtN3G/qOF2DKb2xCON9ihPUfN3bHPv/af+928S4Z2LabasveclzGSmLvgz4S5csO7lm0TyHotC0+MyYmDKYaNMoWZngFI4OgyF2ZcB5uBd4cag5hVPKYXGWZZseTe2OWQuR8IsaA9o2hXH91zv2C9n4cmGgXbe6INvSKWQKl3dCYmtpIcXEXkAiLhMsD5z9FQUle39azVAjKMcb+K1xgyp+7m1mcdHEohPqV3CQjN1GuP/r31HD2wujqfe0k="
      on:
          branch: master
before_deploy:
    - >
      if [[ $TRAVIS_BRANCH == "master" ]]; then
        gh release delete nightly -R ${TRAVIS_REPO_SLUG} -y
        git tag -f nightly || true &&
        git remote add gh https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git &&
        git push --delete -f gh nightly || true &&
        git push -f gh nightly || true
      fi
