language : bash
env:
    global:
      - HUB_PROTOCOL=https
      #GITHUB_TOKEN
      - secure: "wAV9U0ZFAIvUE0YVWQkjUpbgXHCZd711/FfelIAS61+ZDR2zcEf7eIClgMB3XX1Ck7LX0lSnt7SgrNDW9JxV7QNgKO3iBt8ZE10r06isdun4WWNtgPyTSSRKAfiUR3iVTRZFDWmGC4e434KhJ5wqqZXp5kFbXeSj897JqdJigq0jrkeLEafhvTfkVvnPrWWkoIQ9MZ5GJ0FnRjpV+3hLSWOH6rptUYrMaIfUEhQ8jbAX0vCJ2vk3q0s+BQaW3F6kJD9nIiUzbre0xHKmWZuhwk1w3FpoKasugJ2Emq+WP/t6BRe9OIQ7O9AzbkoP/xbFlkPI9iXTfcuC9zwtksRUYOYry8GyGSyaDxVUqi+LKAGcsTOc5jZXA/s5zXViFSHS+gnH6UAB2n5WJXmmkKX51lqAuYQeybWE8BJcXjMy4/pIHW+jBWPwmxQCcV2rMMf4SQVYmRCgchwJFtMpvS79tILuX6oYQ5v/VdFvX4HDbsx1ikKXiYFDY5a68uPFohiJrCXdtHgjucL8RaHU0SdI9LJ0TX/rlo9Douwh6arh3J2w8W/ICOfNMfPnKRolq34yZ9p1x4SlzNDHbdHBhPja7Sjzea0D+v3UN5Dd50TEZd9BQ0iutug5cowiw+ew3tYocSSyAqFXj7y0Bw5CcTSFTg5/tsWdT5lOVHNRqnMo9w8="
branches:
  except:
  - nightly
git:
  quiet: true
before_install:
    - curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
    - sudo apt-get -qq update
    - sudo apt-get install -y debhelper devscripts fakeroot build-essential po-debconf gh jq
    - openssl aes-256-cbc -K $encrypted_2155243bff9e_key -iv $encrypted_2155243bff9e_iv -in 077CC9F2.gpg.enc -out 077CC9F2.gpg -d
    - gpg --import 077CC9F2.gpg
    - mkdir -p src/usr/bin/
    - wget https://${GITHUB_TOKEN}@api.github.com/repos/CMS-Garden/cmsscanner/releases/latest -O - | jq '.assets[] | select(.name == "cmsscanner.phar").browser_download_url' |xargs wget -O src/usr/bin/cmsscanner
    - chmod +x src/usr/bin/cmsscanner
install:
    - debuild '-k9D1DC8DD077CC9F2'

